repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        exclude: |
          (?x)(
              ^.gitlab.ci.yml|
          )
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: flake8
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
default_language_version:
  python: python3
